import type { ReactNode } from 'react';
import DeckShell,{Top,Footer,Logo} from './DeckShell';
const K=({children,kind=''}: {children: ReactNode; kind?: string})=><span className={`key ${kind}`}>{children}</span>;
export default function DelcoPDDeck(){const slides=[
<><Top label="MyCTRL × Delaware County Public Defender" n={1} total={11}/><Logo/><h1>Your AI <span className="accent">personal chief of staff</span></h1><p className="lead">Re-Entry · Recovery · Workforce</p><p>One platform. One LifeVault. One clear path forward.<br/><b>Stephanie George</b> · Founder & CEO · Philadelphia, PA</p><K>CTRL</K><Footer>Collaborative infrastructure for the individual</Footer></>,
<><Top label="The problem" n={2} total={11}/><h2>Public defenders don't just practice law. <span className="accent">They triage lives.</span></h2><p className="lead">Clients leave court with orders, probation mandates, treatment requirements, employment deadlines, housing applications and benefits paperwork.</p><div className="card"><h3>No roadmap. No coordinator. No tool connecting all five.</h3><p>The gap between a court order and a completed life is unmanaged.</p></div><Footer>Support continues after the hearing.</Footer></>,
<><Top label="What MyCTRL is" n={3} total={11}/><h2>Not case management software. <span className="teal">A chief of staff for the individual.</span></h2><div className="grid">{[['Describe','“I was just released. I need housing, treatment and a job.”'],['Plan','AI generates personalized steps, deadlines and resources.'],['Track','Secure LifeVault stores documents and monitors progress.'],['Complete','Mandates, treatment and employment in one place.']].map((x,i)=><article className="card"><K kind={i===1?'esc':i===2?'alt':''}>0{i+1}</K><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><p className="lead">Genuinely individual. Every plan is built for one person.</p><Footer>Individual-first · staff-aware · outcome-oriented</Footer></>,
<><Top label="One umbrella" n={4} total={11}/><h2>Three products. <span className="accent">One LifeVault.</span></h2><div className="grid three">{[['ReEntry','Returning citizens — pre-release through 90-day stabilization.'],['Recovery','SUD and behavioral health — navigation with compliance tracking.'],['Workforce','Court-mandated employment — readiness, applications, follow-through.']].map((x,i)=><article className="card"><K kind={i===1?'esc':''}>{x[0].toUpperCase()}</K><h3>MyCTRL {x[0]}</h3><p>{x[1]}</p></article>)}</div><p className="lead">One person might need all three. MyCTRL handles that seamlessly.</p><Footer>One platform · genuinely individual</Footer></>,
<><Top label="How it works" n={5} total={11}/><h2>From “what's going on” to <span className="teal">“what's next.”</span></h2><div className="flow">{[['Tell us','Plain language or upload the paperwork pile.'],['Understand','Identify urgency, dependencies and mandates.'],['Plan','Prioritized steps, deadlines and local resources.'],['Organize','Searchable LifeVault with timeline and documents.'],['Follow through','Reminders, progress and compliance checklists.']].map((x,i)=><div className="step"><b>0{i+1} · {x[0]}</b>{x[1]}</div>)}</div><Footer>Clarity that compounds into follow-through.</Footer></>,
<><Top label="MyCTRL ReEntry" n={6} total={11}/><h2>Every task. Every deadline. <span className="accent">Every resource.</span></h2><div className="timeline">{[['Pre-release','ID, benefits, housing, family plan'],['24 hours','Probation, medication, temporary housing'],['7 days','State ID, Medicaid, SNAP, job readiness, treatment'],['30 days','Employment, housing, transport, banking'],['90 days','Appointments, renewals, compliance']].map(x=><div className="stage"><b>{x[0]}</b>{x[1]}</div>)}</div><p className="lead">Each task has a deadline, a resource link and a status tracker.</p><Footer>Pre-release through stabilization</Footer></>,
<><Top label="MyCTRL Recovery" n={7} total={11}/><h2>Administrative stability is part of <span className="teal">recovery stability.</span></h2><div className="grid">{[['Treatment continuity','Intake, appointments, medication and sober living.'],['Benefits and work','Medicaid, SNAP, SSI/SSDI and job milestones.'],['Compliance','Court-mandated treatment tracking and probation coordination.'],['Outcome','Less friction between clinical contacts; fewer missed appointments.']].map(x=><article className="card"><h3 className="teal">{x[0]}</h3><p>{x[1]}</p></article>)}</div><Footer>Keep recovery and obligations aligned.</Footer></>,
<><Top label="MyCTRL Workforce" n={8} total={11}/><h2>Employment doesn't start with a job offer. <span className="accent">It starts with a plan.</span></h2><div className="card"><ul><li>ID documents and background-check readiness</li><li>Job-readiness assessment and skills inventory</li><li>Application tracking with deadlines</li><li>Interview preparation and follow-through</li><li>Employer verification documentation for court</li></ul></div><p className="lead">Every step tracked. Every requirement documented.</p><Footer>Build momentum one completed step at a time.</Footer></>,
<><Top label="A measurable pilot" n={9} total={11}/><h2>90 days. One unit. <span className="accent">Measurable outcomes.</span></h2><div className="split"><div><div className="bigstat">100</div><p><b>seats</b> · one unit, your choice</p><div className="bigstat teal">$2,500</div><p><b>one-time pilot</b> · 50% credited toward annual license</p></div><div className="card"><h3>Includes</h3><ul><li>Full platform access</li><li>ReEntry + Recovery + Workforce Life Kits</li><li>Institutional dashboard</li><li>Onboarding and impact report</li></ul><p><b>Metrics:</b> plan completion · court adherence · mandate compliance · engagement</p></div></div><Footer>Align on the right measures. Prove what works.</Footer></>,
<><Top label="The force multiplier" n={10} total={11}/><h2>When there's <span className="accent">nothing left to cut.</span></h2><p className="lead">Burnout is real. Resources are disappearing. The county spends <b>$60M</b> a year on a jail where <b>two-thirds come back.</b></p><div className="grid"><div className="card"><div className="bigstat">512</div><p><b>days</b> of support people need — after a program may offer 90.</p></div><div className="card"><div className="bigstat teal">$25</div><p><b>per person</b> for one platform that multiplies every remaining counselor, defender and case manager.</p></div></div><p className="lead">Not another program asking for a budget line. A force multiplier for every hour when no professional is in the room.</p><Footer>Quiet the noise. Create consistency, structure and confidence.</Footer></>,
<><Top label="Align / Prove" n={11} total={11}/><h2>Let's move from a conversation to <span className="accent">a measurable pilot.</span></h2><div className="grid"><article className="card"><K>CTRL</K><h3>ALIGN</h3><p>Align with your existing workflows. No disruption to your office, your attorneys or your systems.</p></article><article className="card"><K kind="esc">ESC</K><h3>PROVE</h3><p>90 days. One unit. Measurable outcomes. If it works, we scale. If it doesn't, you lost nothing.</p></article></div><div className="card"><b>Stephanie George</b><br/>Founder & CEO · LifeCTRL LLC d/b/a MyCTRL<br/>stephanie@mylifectrl.com · mylifectrl.com</div><Footer>MyCTRL × Delaware County Public Defender</Footer></>];return <DeckShell slides={slides} count={11}/>}
